<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc79f3ed605097d695f109650b42d1430
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc79f3ed605097d695f109650b42d1430::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc79f3ed605097d695f109650b42d1430::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitc79f3ed605097d695f109650b42d1430::$classMap;

        }, null, ClassLoader::class);
    }
}
